# Generated by Django 4.0.4 on 2022-05-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('trade_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepoint',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_points', to='employees.employee'),
        ),
    ]
