# Generated by Django 4.0.4 on 2022-05-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_points', '0002_alter_tradepoint_employee'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='trade_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='trade_points.tradepoint', verbose_name='Trade point'),
        ),
    ]
